GET http://127.0.0.1:5001/messages

###

GET http://127.0.0.1:5001/messages/:messageId

###
 
POST  http://127.0.0.1:5001/messages
Content-Type: application/json

{
  "text": "Checking post method",
  "email": "post@post.post"
}

### 

PATCH http://127.0.0.1:5001/messages/:messageId
Content-Type: application/json

{
  "text": "Checking patch method",
  "email": "patch@patch.patch"
}

###

DELETE http://127.0.0.1:5001/messages/:messageId
